export const KEYS = {
	appId: "Ba4WdlP9AQfbBqxFDTnTzGgBGtcpJ7tLTgzhoG9U",
	jsKey: "vJ4XYoGZxbbMNCbUPtkVcoBZ8amyxoeAe9ofU8wK",
	masterKey: "l6A5mYmDLe3H5ukUJ2AHlIkPsZAQdgQUtCERQlQy"
}

export const types = {
	START_PUMPING: 'START_PUMPING',
	STOP_PUMPING: 'STOP_PUMPING',

	OVERHEAD_DIMENSIONS_REQUEST: 'OVERHEAD_DIMENSIONS_REQUEST',
	OVERHEAD_DIMENSIONS_SUCCESS: 'OVERHEAD_DIMENSIONS_SUCCESS',
	OVERHEAD_DIMENSIONS_FAILURE: 'OVERHEAD_DIMENSIONS_FAILURE',

	BASEMENT_DIMENSIONS_REQUEST: 'BASEMENT_DIMENSIONS_REQUEST',
	BASEMENT_DIMENSIONS_SUCCESS: 'BASEMENT_DIMENSIONS_SUCCESS',
	BASEMENT_DIMENSIONS_FAILURE: 'BASEMENT_DIMENSIONS_FAILURE'
}