export const KEYS = {
	appId: "Ba4WdlP9AQfbBqxFDTnTzGgBGtcpJ7tLTgzhoG9U",
	jsKey: "vJ4XYoGZxbbMNCbUPtkVcoBZ8amyxoeAe9ofU8wK",
	masterKey: "l6A5mYmDLe3H5ukUJ2AHlIkPsZAQdgQUtCERQlQy"
}

export const types = {
	START_PUMPING: 'START_PUMPING',
	STOP_PUMPING: 'STOP_PUMPING',
	MAX_HEIGHT_REQUEST: 'MAX_HEIGHT_REQUEST',
	MAX_HEIGHT_SUCCESS: 'MAX_HEIGHT_SUCCESS',
	MAX_HEIGHT_REQUEST: 'MAX_HEIGHT_FAILURE'
}